name: destroy the infrastructure

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Deployment stage'
        required: true
        default: 'dev'
        options:
          - dev
          - qa
          - prod


jobs:
  destroy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read  # <-- ENSURE THIS IS PRESENT
    steps:
      - name: Validate input
        run: |
          if [[ "${{ github.event.inputs.stage }}" != "dev" && "${{ github.event.inputs.stage }}" != "qa" && "${{ github.event.inputs.stage }}" != "prod" ]]; then
            echo "Invalid input: ${{ github.event.inputs.stage }}. Please use one of the following: dev, qa, prod."
            exit 1
          fi
          
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          aws-output: json

      - name: Initialize Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.2.3'

      - name: Terraform Init and Workspace Management
        run: |
          terraform init
          terraform workspace select ${{ github.event.inputs.stage }} || terraform workspace new ${{ github.event.inputs.stage }}
        working-directory: ./terraform

      - name: Apply destroy configuration
        env:
          TF_VAR_github_token: ${{ secrets.GH_TOKEN }}
        run: |
          terraform init
          exit 1
          VAR_FILE="config/${{ github.event.inputs.stage }}.json"
          terraform destroy -var-file="$VAR_FILE" --auto-approve \
            -var "stage=${{ github.event.inputs.stage }}"
        working-directory: ./terraform
