name: destroy the infrastructure 2 # Or "Destroy Infrastructure" for clarity

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Deployment stage'
        required: true
        default: 'dev'
        options:
          - dev
          - qa
          - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate failure
        run: exit 1

      - name: Upload logs as artifact
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: workflow-logs
          path: ${{ github.workspace }}/../../_temp/_github_workflow/  # GitHub's internal log path

  upload_to_s3:
    needs: build
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: workflow-logs

      - name: Upload to S3
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: us-east-1
        run: |
          aws s3 cp workflow-logs/ s3://sumit-4254/logs/${{ github.run_id }}/ --recursive
