name: Upload Failed Workflow Logs to S3

on:
  workflow_run:
    workflows: ["destroy the infrastructure"]
    types:
      - completed

jobs:
  upload_logs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    # You still need 'actions: read' for export-workflow-logs
    # 'id-token: write' is NOT needed if you're not using OIDC
    permissions:
      actions: read # Only this permission is strictly needed now for the GitHub API interaction

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Or @v4 for latest

      - name: Configure AWS Credentials # <--- THIS IS THE ALTERNATIVE BLOCK
        uses: aws-actions/configure-aws-credentials@v1 # Can use @v4 here too
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          aws-output: json # Optional, but generally good practice

      - name: Export Workflow Run Logs
        uses: timorthi/export-workflow-logs@v1.3.0
        with:
          repo-token: ${{ secrets.GH_TOKEN }} # Your existing GH_TOKEN
          run-id: ${{ github.event.workflow_run.id }}
          destination: s3
          aws-region: us-east-1
          s3-bucket-name: sumit-4254
          s3-key: "failed-workflow-logs/${{ github.event.workflow_run.name }}/${{ github.event.workflow_run.created_at }}-${{ github.sha }}-runId-${{ github.event.workflow_run.id }}.zip"
          # When using static keys, you don't need to explicitly pass
          # aws-access-key-id, aws-secret-access-key, aws-session-token
          # to timorthi/export-workflow-logs because aws-actions/configure-aws-credentials
          # will set them as environment variables.
          # The previous error "required: aws-access-key-id, aws-secret-access-key" from timorthi's action
          # likely indicated that it's designed to pick up env vars by default,
          # but was getting confused by *empty* OIDC outputs being explicitly passed.
          # Let's remove them for this static key approach to avoid confusion.
          # (You can remove these 3 lines below if using this static key method)
          # aws-access-key-id: ${{ steps.aws-creds.outputs.aws-access-key-id }}
          # aws-secret-access-key: ${{ steps.aws-creds.outputs.aws-secret-access-key }}
          # aws-session-token: ${{ steps.aws-creds.outputs.aws-session-token }}
