name: Upload Failed Workflow Logs to S3

on:
  workflow_run:
    workflows: ["destroy the infrastructure"] # Your main workflow name
    types:
      - completed

jobs:
  upload_logs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    permissions:
      id-token: write # Required for authenticating with AWS using OIDC
      actions: read   # Required for export-workflow-logs to retrieve workflow logs

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4 # Keep using v4!
        with:
          role-to-assume: arn:aws:iam::339712898435:role/GitHubActionsS3UploadRole # Your IAM Role ARN
          aws-region: us-east-1 # Your AWS Region
        # No 'id' needed for this step if you're not trying to access its outputs.
        # But keeping it doesn't hurt.

      # REMOVE THE 'Verify AWS Credentials (Outputs and Environment Variables)' DEBUG STEP NOW!
      # It has served its purpose and exposes sensitive info.

      - name: Export Workflow Run Logs
        uses: timorthi/export-workflow-logs@v1.3.0
        with:
          repo-token: ${{ secrets.GH_TOKEN }} # Keeping this as per your requirement
          run-id: ${{ github.event.workflow_run.id }}
          destination: s3
          aws-region: us-east-1 # Your AWS Region
          s3-bucket-name: sumit-4254
          s3-key: "failed-workflow-logs/${{ github.event.workflow_run.name }}/${{ github.event.workflow_run.created_at }}-${{ github.sha }}-runId-${{ github.event.workflow_run.id }}.zip"
          # *** REMOVE THESE THREE LINES BELOW! ***
          # They were trying to pass empty outputs.
          # The action should now automatically pick up the environment variables.
          # aws-access-key-id: ${{ steps.aws-creds.outputs.aws-access-key-id }}
          # aws-secret-access-key: ${{ steps.aws-creds.outputs.aws-secret-access-key }}
          # aws-session-token: ${{ steps.aws-creds.outputs.aws-session-token }}
