name: Upload Failed Workflow Logs to S3

on:
  workflow_run:
    workflows: ["destroy the infrastructure"] # Your main workflow name
    types:
      - completed

jobs:
  upload_logs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    permissions:
      id-token: write # Required for authenticating with AWS using OIDC
      actions: read   # Required for export-workflow-logs to retrieve workflow logs

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::339712898435:role/GitHubActionsS3UploadRole # Your IAM Role ARN
          aws-region: us-east-1 # Your AWS Region
        id: aws-creds # Essential for accessing outputs

      - name: Verify AWS Credentials (Outputs and Environment Variables) # <--- CRITICAL DEBUG STEP
        run: |
          echo "--- From Step Outputs ---"
          echo "Access Key ID (output): ${{ steps.aws-creds.outputs.aws-access-key-id }}"
          echo "Secret Access Key (output): ${{ steps.aws-creds.outputs.aws-secret-access-key }}"
          echo "Session Token (output): ${{ steps.aws-creds.outputs.aws-session-token }}"
          
          echo "--- From Environment Variables ---"
          echo "AWS_ACCESS_KEY_ID (env): $AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY (env): $AWS_SECRET_ACCESS_KEY"
          echo "AWS_SESSION_TOKEN (env): $AWS_SESSION_TOKEN"
          
          # This will cause the workflow to fail if any key is missing, for explicit debugging
          if [ -z "${{ steps.aws-creds.outputs.aws-access-key-id }}" ] || \
             [ -z "${{ steps.aws-creds.outputs.aws-secret-access-key }}" ] || \
             [ -z "${{ steps.aws-creds.outputs.aws-session-token }}" ]; then
            echo "::error::AWS credentials outputs are empty!"
            exit 1
          fi
          if [ -z "$AWS_ACCESS_KEY_ID" ] || \
             [ -z "$AWS_SECRET_ACCESS_KEY" ] || \
             [ -z "$AWS_SESSION_TOKEN" ]; then
            echo "::error::AWS credentials environment variables are empty!"
            exit 1
          fi
        shell: bash
        # IMPORTANT: This step exposes sensitive credentials in logs. REMOVE IT after troubleshooting.

      - name: Export Workflow Run Logs
        uses: timorthi/export-workflow-logs@v1.3.0
        with:
          repo-token: ${{ secrets.GH_TOKEN }} # Keeping this as per your requirement
          run-id: ${{ github.event.workflow_run.id }}
          destination: s3
          aws-region: us-east-1
          s3-bucket-name: sumit-4254
          s3-key: "failed-workflow-logs/${{ github.event.workflow_run.name }}/${{ github.event.workflow_run.created_at }}-${{ github.sha }}-runId-${{ github.event.workflow_run.id }}.zip"
          # Explicitly pass credentials obtained from the first step's outputs
          aws-access-key-id: ${{ steps.aws-creds.outputs.aws-access-key-id }}
          aws-secret-access-key: ${{ steps.aws-creds.outputs.aws-secret-access-key }}
          aws-session-token: ${{ steps.aws-creds.outputs.aws-session-token }}
