name: Upload Failed Workflow Logs to S3

on:
  workflow_run:
    workflows: ["destroy the infrastructure"] # Replace with the name of the workflow you want to monitor
    types:
      - completed

jobs:
  upload_logs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    permissions:
      id-token: write # Required for authenticating with AWS using OIDC
      actions: read   # Required for export-workflow-logs to retrieve workflow logs

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::339712898435:role/GitHubActionsS3UploadRole # Your IAM Role ARN
          aws-region: us-east-1 # Your AWS Region
        id: aws-creds # <--- Give this step an ID to access its outputs

      - name: Export Workflow Run Logs
        uses: timorthi/export-workflow-logs@v1.3.0 # Or the latest version
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          destination: s3
          aws-region: us-east-1 # Your AWS Region
          s3-bucket-name: sumit-4254
          s3-key: "failed-workflow-logs/${{ github.event.workflow_run.name }}/${{ github.event.workflow_run.created_at }}-${{ github.sha }}-runId-${{ github.event.workflow_run.id }}.zip"
          # Pass the credentials explicitly from the previous step's outputs
          aws-access-key-id: ${{ steps.aws-creds.outputs.aws-access-key-id }}
          aws-secret-access-key: ${{ steps.aws-creds.outputs.aws-secret-access-key }}
          aws-session-token: ${{ steps.aws-creds.outputs.aws-session-token }} # Session token is crucial for OIDC temporary creds
