name: Upload Failed Workflow Logs to S3

on:
  workflow_run:
    workflows: ["destroy the infrastructure"] # Replace with the name of the workflow you want to monitor
    types:
      - completed

jobs:
  upload_logs:
    runs-on: ubuntu-latest
    # Only run this job if the monitored workflow failed
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    permissions:
      id-token: write # Required for authenticating with AWS using OIDC
      actions: read   # Required for export-workflow-logs to retrieve workflow logs

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.YOUR_AWS_ACCOUNT_ID }}:role/GitHubActionsS3UploadRole # Replace with your IAM Role ARN
          aws-region: us-east-1 # e.g., us-east-1, ap-south-1

      - name: Export Workflow Run Logs
        uses: timorthi/export-workflow-logs@v1.3.0 # Or the latest version
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          destination: s3
          aws-region: us-east-1 # e.g., us-east-1, ap-south-1
          s3-bucket-name: sumit-4254
          s3-key: "failed-workflow-logs/${{ github.event.workflow_run.name }}/${{ github.event.workflow_run.created_at }}-${{ github.sha }}-runId-${{ github.event.workflow_run.id }}.zip"
          # You can customize the s3-key for your desired S3 path/filename.
          # The above example creates a path like:
          # failed-workflow-logs/YourWorkflowName/2025-07-13T08:37:37Z-abcdef123456-runId-12345.zip
